package rules;

import com.bespoke.drinking.model.*;

import java.util.List

global String nextQuestion;

//  Do you like hot or cold drinks?

rule "Question: Do you like hot or cold drinks?"
    when
        $user: User();
        User($preference: preference, eval($preference.getHot() == null));
        User($answeredQuestions: answeredQuestions);
        $answeredQuestion: AnsweredQuestion(question.getText() == "Do you like hot or cold drinks?", processed == false) from $answeredQuestions;
        $hot: Boolean() from accumulate( 
        	Answer($answer: this) from $answeredQuestion.getAnswer(),
            init( Boolean isHot = false; ),
            action( if ($answer.getAnswerNumber() == 0) {isHot = true;}; ),
            result(isHot)
        );
    then
        $preference.setHot($hot);
        $answeredQuestion.setProcessed(true);
        drools.getKnowledgeRuntime().setGlobal("nextQuestion", "Do you drink coffee or tea more?");
        update($user);
end


//  Do you drink coffee or tea more?

rule "Question: Do you drink coffee or tea more?"
    when
        $user: User();
        User($preference: preference, eval($preference.getHot() != null), eval($preference.getHot()));
        User($answeredQuestions: answeredQuestions);
        $answeredQuestion: AnsweredQuestion(question.getText() == "Do you drink coffee or tea more?", processed == false) from $answeredQuestions;
        $hot: Boolean() from accumulate( 
        	Answer($answer: this) from $answeredQuestion.getAnswer(),
            init( Boolean isHot = false; ),
            action( if ($answer.getAnswerNumber() == 0) {isHot = true;}; ),
            result(isHot)
        );
    then
        //$preference.setHot($hot);
        $answeredQuestion.setProcessed(true);
        update($user);
end

// How do you drink your coffee
