package sbnz.integracija;

import com.bespoke.drinking.model.User;
import com.bespoke.drinking.model.Question;
import com.bespoke.drinking.model.Answer;
import com.bespoke.drinking.model.Preference;

import java.util.List

//  Do you like hot or cold drinks?

rule "Question: Do you like hot or cold drinks?"
    when
        $user: User();
        User($preference: preference, eval($preference.getHot() == null));
        User($answeredQuestions: answeredQuestions);
        $question: Question(text == "Do you like hot or cold drinks?", processed == false) from $answeredQuestions;
        $hot: Boolean() from accumulate( 
        	Answer($answer: this) from $question.getSelectedAnswer(),
            init( Boolean isHot = false; ),
            action( if ($answer.getAnswerNumber() == 0) {isHot = true;}; ),
            result(isHot)
        );
    then
        $preference.setHot($hot);
        $question.setProcessed(true);
        update($user);
end


//  Do you drink coffee or tea more?

rule "Question: Do you drink coffee or tea more?"
    when
        $user: User();
        User($preference: preference, eval($preference.getHot() != null), eval($preference.getHot()));
        User($answeredQuestions: answeredQuestions);
        $question: Question(text == "Do you drink coffee or tea more?", processed == false) from $answeredQuestions;
        $hot: Boolean() from accumulate( 
        	Answer($answer: this) from $question.getSelectedAnswer(),
            init( Boolean isHot = false; ),
            action( if ($answer.getAnswerNumber() == 0) {isHot = true;}; ),
            result(isHot)
        );
    then
        //$preference.setHot($hot);
        $question.setProcessed(true);
        update($user);
end

// How do you drink your coffee
